// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWRaKaml5y6eAxD62Ryj1whHTM7geebfU',
    appId: '1:35891034322:web:26ef1c2d8282548206d50b',
    messagingSenderId: '35891034322',
    projectId: 'personal-finance-c2c80',
    authDomain: 'personal-finance-c2c80.firebaseapp.com',
    storageBucket: 'personal-finance-c2c80.firebasestorage.app',
    measurementId: 'G-EQDB1CE7HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzImztjeMRaHx7nCZUrFg9kX8T9WIXoBE',
    appId: '1:35891034322:android:65323c7e991e415f06d50b',
    messagingSenderId: '35891034322',
    projectId: 'personal-finance-c2c80',
    storageBucket: 'personal-finance-c2c80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9M4hmy_UmQsZb5pef9m4upy43YGkA-yc',
    appId: '1:35891034322:ios:632c1360e223ef4706d50b',
    messagingSenderId: '35891034322',
    projectId: 'personal-finance-c2c80',
    storageBucket: 'personal-finance-c2c80.firebasestorage.app',
    iosBundleId: 'com.example.personalFin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9M4hmy_UmQsZb5pef9m4upy43YGkA-yc',
    appId: '1:35891034322:ios:632c1360e223ef4706d50b',
    messagingSenderId: '35891034322',
    projectId: 'personal-finance-c2c80',
    storageBucket: 'personal-finance-c2c80.firebasestorage.app',
    iosBundleId: 'com.example.personalFin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWRaKaml5y6eAxD62Ryj1whHTM7geebfU',
    appId: '1:35891034322:web:4175b07984ad93cc06d50b',
    messagingSenderId: '35891034322',
    projectId: 'personal-finance-c2c80',
    authDomain: 'personal-finance-c2c80.firebaseapp.com',
    storageBucket: 'personal-finance-c2c80.firebasestorage.app',
    measurementId: 'G-LS8YBCP2VM',
  );
}
